spring.application.name=springblog-rest-api

# Database init
database=h2
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.sql.init.data-locations=classpath*:db/${database}/data.sql

# H2 properties
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:springblog_db

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
