# database initialization
database=postgres
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.sql.init.data-locations=classpath*:db/${database}/data.sql

spring.datasource.driver-class-name=${POSTGRES_SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.url=${POSTGRES_SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/springblog_db}

spring.datasource.username=${POSTGRES_SPRING_DATASOURCE_USERNAME:springblog_user}
spring.datasource.password=${POSTGRES_SPRING_DATASOURCE_PASSWORD:postgres_password}

# SQL is written to be idempotent, so we can run it on startup without worrying about duplicates
spring.sql.init.mode=always 