INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('Understanding JDBC', 'Deep dive into Java Database Connectivity.', 'JDBC is a Java API to connect and execute the query with the database.', 'understanding-jdbc', 'PUBLISHED', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('Spring Data JDBC Overview', 'Why use Spring Data JDBC?', 'Spring Data JDBC offers a simple way to use JDBC with Spring.', 'spring-data-jdbc-overview', 'PUBLISHED', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('Thymeleaf Templates', 'Creating dynamic web pages with Thymeleaf.', 'Thymeleaf is a modern server-side Java template engine for both web and standalone environments.', 'thymeleaf-templates', 'PUBLISHED', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('Spring MVC Basics', 'Introduction to Spring Model-View-Controller.', 'Spring Web MVC is the original web framework built on the Servlet API.', 'spring-mvc-basics', 'PUBLISHED', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('Dockerizing Spring Applications', 'How to run Spring Boot in Docker.', 'Containerization is a key part of modern software development.', 'dockerizing-spring-applications', 'PUBLISHED', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('Unit Testing in Spring', 'Best practices for testing your code.', 'Testing is crucial for building robust applications.', 'unit-testing-in-spring', 'DRAFT', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('Microservices Architecture', 'An overview of microservices.', 'Microservices - also known as the microservice architecture - is an architectural style.', 'microservices-architecture', 'PUBLISHED', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('RESTful Web Services', 'Building APIs with Spring Boot.', 'Representational State Transfer (REST) is an architectural style for providing standards between computer systems.', 'restful-web-services', 'PUBLISHED', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('Spring Security Fundamentals', 'Securing your Spring Boot app.', 'Spring Security is a powerful and highly customizable authentication and access-control framework.', 'spring-security-fundamentals', 'PUBLISHED', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('Java 21 Features', 'What is new in Java 21.', 'Java 21 is the latest Long-Term Support (LTS) release of the Java SE platform.', 'java-21-features', 'PUBLISHED', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('SQL Performance Tuning', 'Optimizing your database queries.', 'Performance tuning is the improvement of system performance.', 'sql-performance-tuning', 'PUBLISHED', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('Hibernate vs JDBC', 'Choosing the right data access tech.', 'Hibernate is an ORM tool while JDBC is an API.', 'hibernate-vs-jdbc', 'DRAFT', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('Cloud Native Applications', 'Building for the cloud.', 'Cloud-native development is an approach to building and running applications that exploits the advantages of the cloud computing delivery model.', 'cloud-native-applications', 'PUBLISHED', NOW(), NOW());
INSERT INTO posts (title, description, body, slug, post_status, created_on, updated_on) VALUES ('Spring Boot Actuator', 'Monitoring your application.', 'Spring Boot Actuator includes a number of additional features to help you monitor and manage your application.', 'spring-boot-actuator', 'PUBLISHED', NOW(), NOW());

INSERT INTO comments (post_id, title, AUTHOR_NAME, body, created_on, updated_on) VALUES (1, 'Great Intro', 'John Doe', 'This was a very helpful introduction to Spring Boot.', NOW(), NOW());
INSERT INTO comments (post_id, title, AUTHOR_NAME, body, created_on, updated_on) VALUES (1, 'Thanks!', 'Jane Smith', 'Clear and concise, thank you!', NOW(), NOW());
INSERT INTO comments (post_id, title, AUTHOR_NAME, body, created_on, updated_on) VALUES (2, 'JDBC vs JPA', 'Bob Wilson', 'How does this compare to using JPA?', NOW(), NOW());
INSERT INTO comments (post_id, title, AUTHOR_NAME, body, created_on, updated_on) VALUES (3, 'Thymeleaf Tips', 'Alice Johnson', 'Any tips for using Thymeleaf with Spring Boot?', NOW(), NOW());